### ISSUE TITLE
DOC example of why proppy

### ISSUE THREAD

**Issue by Devric** [fahad19/proppy#1]
Hi. It might help to promote poppy if you put live code example with pros/cons of using poppy vs not using poppy.

I was used to using decorators to compose for react. But now I switch to Vue, and I struggle to find use cases that require to wrap the Vue components.

**Comment by fahad19** [comment]
Hi @Devric! Thanks for your feedback! 🎉 

I will have something written by this weekend.

**Comment by dzek69** [comment]
+1 for examples and I'm especially interested in React examples, as React has idea of state and props built-in (yours is a bit different of course) and I'm insterested how this could help me solve problems or improve my code.

**Comment by dpikt** [comment]
A side-by-side comparison of proppy and recompose would also be appreciated!

**Comment by fahad19** [comment]
> A side-by-side comparison of proppy and recompose would also be appreciated!

I will add it to the homepage along with other examples 👍

**Comment by Devric** [comment]
Perfect! Instant FAN
