### ISSUE TITLE
Testing: how to pass new props when testing factories?

### ISSUE THREAD

**Issue by atomanyih** [fahad19/proppy#29]
What's the recommended way to pass and update props in test?

I'm trying to test this Proppy factory for a timer behavior:

```js
const P = compose(
  withStateHandlers(
    {
      startTime: null
    },
    {
      startTimer: ({t}) => () => ({
        startTime: t
      })
    }
  ),
  map((props) => {
    const {t, startTime, duration} = props;

    if (isNil(startTime)) {
      return {
        ...props,
        timeLeft: duration
      }
    }
    return {
      ...props,
      timeLeft: duration - (t - startTime)
    }
  })
)
```

On a high level the factory works like this:
1. you pass in `t` (the current time)
1. `timeLeft` is passed to child
1. at some point the child calls `startTimer`
1. the relentless advance of time causes `t` to change
1.  updated `timeLeft` is passed to child

the example [here](https://proppyjs.com/docs/testing/) shows how to test a fairly trivial proppy factory, but I'm not sure how to simulate the behavior outlined above.

after some experimentation, I was able to pass in the initial props (see below) but it feels kinda clunky and wrong. I'm also not clear on how to pass new props into the same instance (simulating the passage of time)

```js
const P = compose(
  withProps({t: 0, duration: 180000}),
   behavior
);

const p = P();

expect(p.props.timeLeft).toEqual(180000)

p.props.startTimer();

// rerender with new props??

expect(p.props.timeLeft).toEqual(170000)

```

Thanks!

**Comment by fahad19** [comment]
@atomanyih: one positive thing of Proppy factory is you can create a instance out of it with another parent instance.

For example, you can have a Proppy instance that takes care of setting timer:

```js
const Base = withState('n', 'setN', 0);

const base = Base();

// update as you wish later
base.setN(10);
base.setN(20);
```

Your own factory may look like:

```js
const P = map(props => props);
```

But when testing, the instance can have the base as a parent:

```js
const p = P(providers, base);
```

You are now free to inject new props to `p` by using the `base` instance:

```js
base.setN(50);
```
