### ISSUE TITLE
Proppy subscribers are non removed properly

### ISSUE THREAD

**Issue by reaktivo** [fahad19/proppy#31]
Hey Fahad! Great job on Proppy, I've been quite amazed by the project so far but ran into a small bug:

The implementation of `removeCallback` will not remove all handlers when .destroy is called, you can see an example here:

https://codesandbox.io/s/o499mj9nxy?expanddevtools=1&module=%2Fsrc%2Findex.js

**Comment by fahad19** [comment]
@reaktivo: Marcel!!! :D 

Thanks for the kind words, mate! I will take a look at your PR when home and take action soon. 

Cheers!
