### ISSUE TITLE
Sharing state between components

### ISSUE THREAD

**Issue by YahngSungho** [fahad19/proppy#36]
![proppy1](https://user-images.githubusercontent.com/29212791/45930595-210beb00-bf9d-11e8-88bf-4ca73ce9bf7f.gif)

Please refer to the attached gif file.

I tried it the other way, but ``this.props.setMessages(something)`` did not change ``this.props.messages``, with 
``const Proppy = compose(
  withState('messages', 'setMessages', [])
) ``
and 
``attach(Proppy)(MyComponent).``

It's not complicated at all, so I might have done something wrong, but I do not know what it is. What parts should I check again?

**Comment by YahngSungho** [comment]
After a couple of experiments, perhaps the problem is that when calling setter() in attach(P)(Comp1), Comp1 is re-rendered, but other attach(P)(Comp2) is not. 
Is this the intended behavior of Proppy? Can not multiple components share state through attach?

**Comment by fahad19** [comment]
Hi @YahngSungho,

It is important to understand the different between Factories and Instances in ProppyJS: https://proppyjs.com/docs/factory-instance/

This is a factory:

```js
const Proppy = compose(
  withState('messages', 'setMessages', [])
)
```

And you attach the Factory to your Component:

```js
export default attach(Proppy)(MyComponent)
```

Now when the `MyComponent` is initialized, it will create an instance out of the ProppyJS factory, and then use it for `MyComponent` alone.

Same happens with `ChatWindow` component is initialized, and it has its own ProppyJS instance.

Meaning, the ProppyJS instances are not shared between the two components.

That's where Providers come into play: https://proppyjs.com/docs/providers/

They allow you to share common dependencies of your application throughout the whole components-tree. 

If you want to share state between components, I recommend using something like a Store, like Redux for example. There is an integration for that here: https://proppyjs.com/docs/packages/proppy-redux/

Full example: 

* Setting Redux store as Provider: https://github.com/fahad19/proppy/blob/master/examples/react-playground/src/index.js#L17
* Rest of the app: https://github.com/fahad19/proppy/tree/master/examples/react-playground/src/proppy-redux
