### ISSUE TITLE
drop in recompose replacement?

### ISSUE THREAD

**Issue by JiLiZART** [fahad19/proppy#44]
Is there solution to replace `recompose` with this library without rewrithing whole project.
We have about ~100K LOC

**Comment by fahad19** [comment]
Hi @JiLiZART!

ProppyJS was inspired by recompose, but not build as a replacement. Recompose creates components with each composed function, while Proppy will create only one component in the tree no matter how many functions you use.

I don't have any plans to write codemods for this, but would welcome any contribution. 

Cheers
